__author__ = 'azhar'
from django.conf.urls import patterns
from django.conf.urls import url
from views import *

urlpatterns = patterns(
    url(r'', index),
    url(r'^login/$', login_admin_view),
    url(r'^members/$', members_view),
    url(r'^members/categories/$', categories_view, name='cat_view'),
    url(r'^members/categories/skills', skills_view),
    url(r'^members/logout', logout_view),
    url(r'^members/categories/add_category', process_catadd),   #this is for adding categories
    url(r'^members/categories/enable/', process_enable_status),
    url(r'^members/categories/disable/', process_disable_status),
    url(r'^members/categories/delete/', process_delete_status),
    url(r'^members/categories/edit/(?P<editid>[0-9]+)/$', process_edit_form),
    url(r'^members/categories/editcategory/$', process_category_edit),
    url(r'^members/categories/skill_enable/$', skill_view_enable),
    url(r'^members/categories/skill_disable/$', skill_view_disable),
    url(r'^members/categories/skill_delete/$', skill_view_delete),
    url(r'^members/categories/skill/edit/(?P<edit>[0-9]+)/$', skills_view),
    url(r'^members/skills/add/$', skill_add),
    url(r'^members/education/$', EducationView.as_view()),
    url(r'^members/education/delete/$', education_delete),
    url(r'^members/education/enable/$', education_enable),
    url(r'^members/education/disable/$', education_disable),
    url(r'^members/education/edit/$', education_edit),
    url(r'^members/users/$', users_view),
    url(r'^members/users/allusers/$',User_View.as_view(), name="User_View"),
    url(r'^members/users/edit_profile/$', test_userinfo),
    url(r'^members/users/edit_profile/update_user/$', user_update),
    url(r'^members/users/edit_profile/add_user/$', user_add),
    url(r'^members/users/edit_profile/delete_user/$', user_delete),
    url(r'^members/users/edit_profile/search/$', user_search),
    url(r'^members/users/edit_profile/get_id/$', get_id),
    url(r'^members/users/edit_profile/allusers/$', allusers),
    url(r'^members/users/edit_profile/activeusers/$', activeusers),
    url(r'^members/users/edit_profile/nonactiveusers/$', nonactiveusers),
    url(r'^members/users/activeusers/$', activeusers),
    url(r'^members/users/edit_profile/nonactiveusers/$', nonactiveusers),
    url(r'^members/users/edit_profile/profilestatus/$', getprofilestatus),
    url(r'^members/users/edit_profile/companyfilter/$', companyfilter),
    url(r'^members/users/edit_profile/job_seekerfilter/$', job_seekerfilter),
    url(r'^members/employment/$', EmploymentView.as_view()),
    url(r'^members/employment/delete/$', employment_delete),
    url(r'^members/employment/enable/$', employment_enable),
    url(r'^members/employment/disable/$', employment_disable),
    url(r'^members/employment/edit/$', employment_edit),
    url(r'^members/experience/$', ExperienceView.as_view()),
    url(r'^members/experience/delete/$', experience_delete),
    url(r'^members/experience/enable/$', experience_enable),
    url(r'^members/experience/disable/$', experience_disable),
    url(r'^members/experience/edit/$', experience_edit),
    url(r'^members/evaluation/$', evaluation_index),
    url(r'^members/evaluation/default/$', evaluation_default),
    url(r'^members/evaluation/user/$', evaluation_user),
    url(r'^members/evaluation/user_pending/$', evaluation_user_pending),
    url(r'^members/evaluation/user_approved/$', evaluation_user_approved),
    url(r'^members/evaluation/user_rejected/$', evaluation_user_rejected),
    url(r'^members/evaluation/edit_question/(?P<id>[0-9]+)/$', edit_evaluation_question),
    url(r'^members/evaluation/add_template/$', addtemplate),
    url(r'^members/evaluation/reject_evaluation/$', reject_evaulation),
    url(r'^members/evaluation/approve_evaluation/$', approve_evaulation),
    url(r'^members/evaluation/edit_user_template/$',edit_user_template_by_admin),
    url(r'^members/advertisement/$', list_all_advertisement,name='list_all_advertisement'),
    url(r'^members/advertisement/edit/$', edit_job_advertisement,name='edit_advertisement'),
    url(r'^members/advertisement/edit_job/$', edit_job_details,name='edit_job_advertisement'),
    url(r'^members/advertisement/enable_job/$', enable_job,name='enable_job_advertisement'),
    url(r'^members/advertisement/disable_job/$', disable_job ,name='disable_job_advertisement'),
    url(r'^members/advertisement/reject_job/$', reject_job ,name='reject_job_advertisement')


)

