INSERT into core_countries(country_name)VALUES("Afghanistan");
INSERT into core_countries(country_name)VALUES("Albania");
INSERT into core_countries(country_name)VALUES("Algeria");
INSERT into core_countries(country_name)VALUES("Andorra");
INSERT into core_countries(country_name)VALUES("Angola");
INSERT into core_countries(country_name)VALUES("Antigua and Barbuda");
INSERT into core_countries(country_name)VALUES("Argentina");
INSERT into core_countries(country_name)VALUES("Armenia");
INSERT into core_countries(country_name)VALUES("Australia");
INSERT into core_countries(country_name)VALUES("Austria");
INSERT into core_countries(country_name)VALUES("Azerbaijan");
INSERT into core_countries(country_name)VALUES("Bahamas");
INSERT into core_countries(country_name)VALUES("Bahrain");
INSERT into core_countries(country_name)VALUES("Bangladesh");
INSERT into core_countries(country_name)VALUES("Barbados");
INSERT into core_countries(country_name)VALUES("Belarus");
INSERT into core_countries(country_name)VALUES("Belgium");
INSERT into core_countries(country_name)VALUES("Belize");
INSERT into core_countries(country_name)VALUES("Benin");
INSERT into core_countries(country_name)VALUES("Bhutan");
INSERT into core_countries(country_name)VALUES("Bolivia");
INSERT into core_countries(country_name)VALUES("Bosnia and Herzegovina");
INSERT into core_countries(country_name)VALUES("Botswana");
INSERT into core_countries(country_name)VALUES("Brazil");
INSERT into core_countries(country_name)VALUES("Brunei");
INSERT into core_countries(country_name)VALUES("Bulgaria");
INSERT into core_countries(country_name)VALUES("Burkina Faso");
INSERT into core_countries(country_name)VALUES("Burundi");
INSERT into core_countries(country_name)VALUES("Cabo Verde");
INSERT into core_countries(country_name)VALUES("Cambodia");
INSERT into core_countries(country_name)VALUES("Cameroon");
INSERT into core_countries(country_name)VALUES("Canada");
INSERT into core_countries(country_name)VALUES("Central African Republic");
INSERT into core_countries(country_name)VALUES("Chad");
INSERT into core_countries(country_name)VALUES("Chile");
INSERT into core_countries(country_name)VALUES("China");
INSERT into core_countries(country_name)VALUES("Colombia");
INSERT into core_countries(country_name)VALUES("Comoros");
INSERT into core_countries(country_name)VALUES("Congo, Republic of the");
INSERT into core_countries(country_name)VALUES("Congo, Democratic Republic of the");
INSERT into core_countries(country_name)VALUES("Costa Rica");
INSERT into core_countries(country_name)VALUES("Cote d'Ivoire");
INSERT into core_countries(country_name)VALUES("Croatia");
INSERT into core_countries(country_name)VALUES("Cuba");
INSERT into core_countries(country_name)VALUES("Cyprus");
INSERT into core_countries(country_name)VALUES("Czech Republic");
INSERT into core_countries(country_name)VALUES("Denmark");
INSERT into core_countries(country_name)VALUES("Djibouti");
INSERT into core_countries(country_name)VALUES("Dominica");
INSERT into core_countries(country_name)VALUES("Dominican Republic");
INSERT into core_countries(country_name)VALUES("Ecuador");
INSERT into core_countries(country_name)VALUES("Egypt");
INSERT into core_countries(country_name)VALUES("El Salvador");
INSERT into core_countries(country_name)VALUES("Equatorial Guinea");
INSERT into core_countries(country_name)VALUES("Eritrea");
INSERT into core_countries(country_name)VALUES("Estonia");
INSERT into core_countries(country_name)VALUES("Ethiopia");
INSERT into core_countries(country_name)VALUES("Fiji");
INSERT into core_countries(country_name)VALUES("Finland");
INSERT into core_countries(country_name)VALUES("France");
INSERT into core_countries(country_name)VALUES("Gabon");
INSERT into core_countries(country_name)VALUES("Gambia");
INSERT into core_countries(country_name)VALUES("Georgia");
INSERT into core_countries(country_name)VALUES("Germany");
INSERT into core_countries(country_name)VALUES("Ghana");
INSERT into core_countries(country_name)VALUES("Greece");
INSERT into core_countries(country_name)VALUES("Grenada");
INSERT into core_countries(country_name)VALUES("Guatemala");
INSERT into core_countries(country_name)VALUES("Guinea");
INSERT into core_countries(country_name)VALUES("Guinea-Bissau");
INSERT into core_countries(country_name)VALUES("Guyana");
INSERT into core_countries(country_name)VALUES("Haiti");
INSERT into core_countries(country_name)VALUES("Honduras");
INSERT into core_countries(country_name)VALUES("Hungary");
INSERT into core_countries(country_name)VALUES("Iceland");
INSERT into core_countries(country_name)VALUES("India");
INSERT into core_countries(country_name)VALUES("Indonesia");
INSERT into core_countries(country_name)VALUES("Iran");
INSERT into core_countries(country_name)VALUES("Iraq");
INSERT into core_countries(country_name)VALUES("Ireland");
INSERT into core_countries(country_name)VALUES("Israel");
INSERT into core_countries(country_name)VALUES("Italy");
INSERT into core_countries(country_name)VALUES("Jamaica");
INSERT into core_countries(country_name)VALUES("Japan");
INSERT into core_countries(country_name)VALUES("Jordan");
INSERT into core_countries(country_name)VALUES("Kazakhstan");
INSERT into core_countries(country_name)VALUES("Kenya");
INSERT into core_countries(country_name)VALUES("Kiribati");
INSERT into core_countries(country_name)VALUES("Kosovo");
INSERT into core_countries(country_name)VALUES("Kuwait");
INSERT into core_countries(country_name)VALUES("Kyrgyzstan");
INSERT into core_countries(country_name)VALUES("Laos");
INSERT into core_countries(country_name)VALUES("Latvia");
INSERT into core_countries(country_name)VALUES("Lebanon");
INSERT into core_countries(country_name)VALUES("Lesotho");
INSERT into core_countries(country_name)VALUES("Liberia");
INSERT into core_countries(country_name)VALUES("Libya");
INSERT into core_countries(country_name)VALUES("Liechtenstein");
INSERT into core_countries(country_name)VALUES("Lithuania");
INSERT into core_countries(country_name)VALUES("Luxembourg");
INSERT into core_countries(country_name)VALUES("Macedonia");
INSERT into core_countries(country_name)VALUES("Madagascar");
INSERT into core_countries(country_name)VALUES("Malawi");
INSERT into core_countries(country_name)VALUES("Malaysia");
INSERT into core_countries(country_name)VALUES("Maldives");
INSERT into core_countries(country_name)VALUES("Mali");
INSERT into core_countries(country_name)VALUES("Malta");
INSERT into core_countries(country_name)VALUES("Marshall Islands");
INSERT into core_countries(country_name)VALUES("Mauritania");
INSERT into core_countries(country_name)VALUES("Mauritius");
INSERT into core_countries(country_name)VALUES("Mexico");
INSERT into core_countries(country_name)VALUES("Micronesia");
INSERT into core_countries(country_name)VALUES("Moldova");
INSERT into core_countries(country_name)VALUES("Monaco");
INSERT into core_countries(country_name)VALUES("Mongolia");
INSERT into core_countries(country_name)VALUES("Montenegro");
INSERT into core_countries(country_name)VALUES("Morocco");
INSERT into core_countries(country_name)VALUES("Mozambique");
INSERT into core_countries(country_name)VALUES("Myanmar (Burma)");
INSERT into core_countries(country_name)VALUES("Namibia");
INSERT into core_countries(country_name)VALUES("Nauru");
INSERT into core_countries(country_name)VALUES("Nepal");
INSERT into core_countries(country_name)VALUES("Netherlands");
INSERT into core_countries(country_name)VALUES("New Zealand");
INSERT into core_countries(country_name)VALUES("Nicaragua");
INSERT into core_countries(country_name)VALUES("Niger");
INSERT into core_countries(country_name)VALUES("Nigeria");
INSERT into core_countries(country_name)VALUES("North Korea");
INSERT into core_countries(country_name)VALUES("Norway");
INSERT into core_countries(country_name)VALUES("Oman");
INSERT into core_countries(country_name)VALUES("Pakistan");
INSERT into core_countries(country_name)VALUES("Palau");
INSERT into core_countries(country_name)VALUES("Palestine");
INSERT into core_countries(country_name)VALUES("Panama");
INSERT into core_countries(country_name)VALUES("Papua New Guinea");
INSERT into core_countries(country_name)VALUES("Paraguay");
INSERT into core_countries(country_name)VALUES("Peru");
INSERT into core_countries(country_name)VALUES("Philippines");
INSERT into core_countries(country_name)VALUES("Poland");
INSERT into core_countries(country_name)VALUES("Portugal");
INSERT into core_countries(country_name)VALUES("Qatar");
INSERT into core_countries(country_name)VALUES("Romania");
INSERT into core_countries(country_name)VALUES("Russia");
INSERT into core_countries(country_name)VALUES("Rwanda");
INSERT into core_countries(country_name)VALUES("St. Kitts and Nevis");
INSERT into core_countries(country_name)VALUES("St. Lucia");
INSERT into core_countries(country_name)VALUES("St. Vincent and The Grenadines");
INSERT into core_countries(country_name)VALUES("Samoa");
INSERT into core_countries(country_name)VALUES("San Marino");
INSERT into core_countries(country_name)VALUES("Sao Tome and Principe");
INSERT into core_countries(country_name)VALUES("Saudi Arabia");
INSERT into core_countries(country_name)VALUES("Senegal");
INSERT into core_countries(country_name)VALUES("Serbia");
INSERT into core_countries(country_name)VALUES("Seychelles");
INSERT into core_countries(country_name)VALUES("Sierra Leone");
INSERT into core_countries(country_name)VALUES("Singapore");
INSERT into core_countries(country_name)VALUES("Slovakia");
INSERT into core_countries(country_name)VALUES("Slovenia");
INSERT into core_countries(country_name)VALUES("Solomon Islands");
INSERT into core_countries(country_name)VALUES("Somalia");
INSERT into core_countries(country_name)VALUES("South Africa");
INSERT into core_countries(country_name)VALUES("South Korea");
INSERT into core_countries(country_name)VALUES("South Sudan");
INSERT into core_countries(country_name)VALUES("Spain");
INSERT into core_countries(country_name)VALUES("Sri Lanka");
INSERT into core_countries(country_name)VALUES("Sudan");
INSERT into core_countries(country_name)VALUES("Suriname");
INSERT into core_countries(country_name)VALUES("Swaziland");
INSERT into core_countries(country_name)VALUES("Sweden");
INSERT into core_countries(country_name)VALUES("Switzerland");
INSERT into core_countries(country_name)VALUES("Syria");
INSERT into core_countries(country_name)VALUES("Taiwan");
INSERT into core_countries(country_name)VALUES("Tajikistan");
INSERT into core_countries(country_name)VALUES("Tanzania");
INSERT into core_countries(country_name)VALUES("Thailand");
INSERT into core_countries(country_name)VALUES("Timor-Leste");
INSERT into core_countries(country_name)VALUES("Togo");
INSERT into core_countries(country_name)VALUES("Tonga");
INSERT into core_countries(country_name)VALUES("Trinidad and Tobago");
INSERT into core_countries(country_name)VALUES("Tunisia");
INSERT into core_countries(country_name)VALUES("Turkey");
INSERT into core_countries(country_name)VALUES("Turkmenistan");
INSERT into core_countries(country_name)VALUES("Tuvalu");
INSERT into core_countries(country_name)VALUES("Uganda");
INSERT into core_countries(country_name)VALUES("Ukraine");
INSERT into core_countries(country_name)VALUES("United Arab Emirates");
INSERT into core_countries(country_name)VALUES("UK (United Kingdom)");
INSERT into core_countries(country_name)VALUES("USA (United States of America)");
INSERT into core_countries(country_name)VALUES("Uruguay");
INSERT into core_countries(country_name)VALUES("Uzbekistan");
INSERT into core_countries(country_name)VALUES("Vanuatu");
INSERT into core_countries(country_name)VALUES("Vatican City (Holy See)");
INSERT into core_countries(country_name)VALUES("Venezuela");
INSERT into core_countries(country_name)VALUES("Vietnam");
INSERT into core_countries(country_name)VALUES("Yemen");
INSERT into core_countries(country_name)VALUES("Zambia");
INSERT into core_countries(country_name)VALUES("Zimbabwe");