"""
Django settings for jobsinsider_app project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from unipath import Path

BASE_DIR = Path(__file__).ancestor(2)
# STATIC_ROOT = BASE_DIR.child('assets')
MEDIA_ROOT = BASE_DIR.child('media')
STATICFILES_DIRS = (
    BASE_DIR.child("assets"),
    # BASE_DIR.child("static"),
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'gq+6u=92e#i#_&yk-#g75iinbcew+z8mcly7p*pcl@8s(%clv='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'twitter_bootstrap',
    'accounts',
    'core'
    )

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'jobsinsider_app.urls'


# Accounts directory
TEMP_DIRECTORY_REGISTER = [
    'templates/accounts/registration',
]

# Email Templates for Accounts
TEMP_DIRECTORY_EMAILS = [
    'templates/accounts/emails',
]



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': (
            BASE_DIR.child('templates'),
            BASE_DIR.join(TEMP_DIRECTORY_REGISTER),
            BASE_DIR.join(TEMP_DIRECTORY_EMAILS),


        ),
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jobsinsider_app.wsgi.application'


TEMPLATE_DIRS = (


)

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'jobsinsider',
        'USER': 'root',
        'PASSWORD': 'gonein60sec',
        'HOST': 'localhost',
        'PORT': '3306',
        }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/assets/'

# Email Configuration

EMAIL_HOST = 'smtp.critsend.com'
EMAIL_HOST_USER = 'waqar@techpointmedia.com'
EMAIL_HOST_PASSWORD = 'nC5pDMz6cC8W2'
EMAIL_PORT = 587
EMAIL_USE_TLS = True